<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.14.2" />
		<PackageReference Include="FluentValidation" Version="12.0.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
		<PackageReference Include="Microsoft.Graph" Version="5.88.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DomainModel.Shared\Domain.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UserAdministration\Services\" />
	</ItemGroup>

</Project>
