version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/MuffiNet.FrontendReact/ClientApp/package.json"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/" 
    schedule:
      interval: "weekly"
