version: "2"
exclude_patterns:
  - src/MuffiNet.Backend/Data/Migrations/**
  - src/MuffiNet.FrontendReact/wwwroot/**
  - src/MuffiNet.FrontendReact/Startup.cs
  - src/MuffiNet.FrontendReact/Program.cs
  - src/MuffiNet.FrontendReact/Areas/Identity/**
  - src/MuffiNet.FrontendReact/ClientApp/src/authorization/**
  - tests/**

plugins:
  # https://docs.codeclimate.com/docs/fixme
  fixme:
    enabled: true
