version: "2"
exclude_patterns:
  - src/MuffiNet.Backend/Data/Migrations/**
  - src/MuffiNet.FrontendReact/wwwroot/**
  - src/MuffiNet.FrontendReact/Startup.cs

plugins:
  # https://docs.codeclimate.com/docs/fixme
  fixme:
    enabled: true
