version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 127.0.0.1:1433:1433
    volumes:
      - mssqldata:/var/opt/mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password1234"

volumes:
  mssqldata:
