export const ApplicationPaths = {
  DefaultLoginRedirectPath: string,
  ApiAuthorizationClientConfigurationUrl: string,
  ApiAuthorizationPrefix: string,
  Login: string,
  LoginFailed: string,
  LoginCallback: string,
  Register: string,
  Profile: string,
  LogOut: string,
  //LoggedOut: string,
  LoggedOut: string,
  LogOutCallback: string,
  IdentityRegisterPath: string,
  IdentityManagePath: string,
}
