# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: CI

on: push

jobs:
  npm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: "src/Client/package.json"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install JS dependencies
        run: npm ci --prefix src/Client --no-audit --prefer-offline
      - name: Run JS linters
        run: npm run lint --prefix src/Client

  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4
        with:
          node-version-file: "src/Client/package.json"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install JS dependencies
        run: npm ci --prefix src/Client --no-audit --prefer-offline
      - name: Run JS test
        run: npm run test --prefix src/Client

  dotnet-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Start MSSQL DB
        run: docker-compose up -d

      - uses: actions/setup-node@v4
        with:
          node-version-file: "src/Client/package.json"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3

      - name: Install dotnet ef
        run: dotnet tool install --global dotnet-ef

      - name: Set up playwright
        run: |
          dotnet build tests/EndToEnd.Tests/EndToEnd.Tests.csproj
          pwsh tests/EndToEnd.Tests/bin/Debug/net8.0/playwright.ps1 install chromium

      - name: Test with the dotnet CLI
        run: dotnet test
        env:
          ActiveDirectoryConfig__AppClientSecret: ${{ secrets.ACTIVEDIRECTORYCONFIG__APPCLIENTSECRET }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - npm-lint
      - npm-test
      - dotnet-test
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Attempt connection to unpause Azure serverless sql db
        continue-on-error: true
        uses: azure/sql-action@v2.2
        with:
          server-name: muffi-net-sql-server
          connection-string: ${{ secrets.MSSQL_CONNECTION_STRING }}
          sql-file: "./sql/create-user.sql"

      - uses: actions/setup-node@v4
        with:
          node-version-file: "src/Client/package.json"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3

      - name: Publish
        run: dotnet publish src/Api.WithReact/Api.WithReact.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v3
        with:
          app-name: muffi-net
          slot-name: Production
          publish-profile: ${{ secrets.AzurePublishProfile }}
          package: ${{env.DOTNET_ROOT}}/myapp

      - name: Run database migrations
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef database update --startup-project src/Api.WithReact --project src/Infrastructure
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: ${{ secrets.MSSQL_CONNECTION_STRING }}
